### ISSUE TITLE
Basic Auth example wording is wrong

### ISSUE THREAD

**Issue by btutal** [NatLibFi/passport-atlassian-crowd-js#3]
Not an actual issue but app: and password: in Basic Auth example should be changed as below, 

```
passport.use(new BasicStrategy({
    url: CROWD_URL, appName: CROWD_APP_NAME, appPassword: CROWD_APP_PASSWORD
}));
```
I didn't want to create pull request just for this but wanted to share since it took some time for me to figure out what's wrong with my code.  Didn't have a chance to check Bearer strategies but I assume it would apply to them as well.

**Comment by natlibfi-arlehiko** [comment]
Cheers! Fixed and published a new version to NPM so that the README's updated there as well.
